mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restourant_menu.urls'))
]

restourant_menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.MenuList.as_view(), name="home"),

]

restourant_menu/models.py
from django.db import models
from django.contrib.auth.models import User

MEAL_TYPE = (
    ("starters", "Starters"),
    ("salads", "Salads"),
    ("main_dishes", "Main Dishes"),
    ("desserts", "Desserts"),
)

STATUS = (
    (0, "Unavailable"),
    (1, "Available"),
)


class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True);
    description = models.CharField(max_length=2000);
    price = models.DecimalField(max_digits=6, decimal_places=2);
    meal_type = models.CharField(max_length=50, choices=MEAL_TYPE);
    author = models.ForeignKey(User, on_delete=models.PROTECT);
    status = models.IntegerField(choices=STATUS, default=0);
    date_created = models.DateTimeField(auto_now_add=True);
    date_update = models.DateTimeField(auto_now=True);

    def __str__(self):
        return self.meal;

restourant_menu/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, MEAL_TYPE

class MenuList(generic.ListView):
    queryset = Item.objects.order_by("-date_created")
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meals"] = MEAL_TYPE
        return context

class MenuItemDetail(generic.DetailView):
    model = Item
    template_name = "menu_item_detail.html"

restourant_menu/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>
      Restaurant menu
  </h1>
  {% for meal in meals %}
       <h3>{{ meal.1 }}</h3>
          {% for row in item_list %}
              {% if row.meal_type == meal.0 %}
                 {% if row.status == 0 %}
                        <h3><del>{{ row.meal }}</del></h3>>
                        <p>{{ row.description }}</p>
                    {% else %}
                        <h3>{{ row.meal }}</h3>>
                        <p>{{ row.description }}</p>
                 {% endif %}
              {% endif %}
          {% endfor %}
  {% endfor %}
</body>
</html>

restourant_menu/templates/menu_item_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Menu item</h1>
</body>
</html>

templates/menu_item_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>